# Default worker is for dev only.
# See omaps and organicmaps environments below for production.
name = 'meta-dev'
main = 'src/index.ts'
compatibility_date = '2022-11-21'
# Organic Maps CF Account ID.
account_id = '462f578f0939f041e2c24ec99adce458'
workers_dev = true
# Whether Wrangler should send usage metrics to Cloudflare for this project.
send_metrics = false

[build]
command = 'npm ci --prefer-offline --no-audit && npm run build'

[vars]
DEBUG = true

[env.prod]
name = 'meta'
workers_dev = false
# See the full list of handled paths in the code.
route = 'meta.omaps.app/*'

[env.prod.vars]
DEBUG = false
